#!/usr/bin/env bash
# scripts/new-worktree.sh <branch-name> [base-port]
# Creates a new git worktree in a sibling directory with an isolated Docker Compose
# project name and port allocation.
#
# COMPOSE_PROJECT_NAME isolation ensures containers, networks, and volumes from
# different worktrees never conflict — Docker prefixes everything with it.
#
# Example:
#   make worktree BRANCH=feature/new-plugin PORT=4010
#   # Creates ../redmine-feature-new-plugin/ with its own .env
#   # cd ../redmine-feature-new-plugin && make start  → starts on port 4010
set -euo pipefail

BRANCH="${1:?ERROR: branch name required. Usage: $0 <branch-name> [base-port]}"
BASE_PORT="${2:-4010}"
TEST_PORT=$((BASE_PORT + 1))

# Sanitize branch name into a Docker-safe slug
SLUG=$(echo "$BRANCH" | tr '/' '-' | tr '_' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g' | sed 's/^-*//' | sed 's/-*$//')
PROJECT_NAME="redmine-${SLUG}"
WORKTREE_DIR="$(pwd)/../redmine-${SLUG}"

echo "Creating git worktree..."
echo "  Branch:               ${BRANCH}"
echo "  Directory:            ${WORKTREE_DIR}"
echo "  COMPOSE_PROJECT_NAME: ${PROJECT_NAME}"
echo "  REDMINE_PORT:         ${BASE_PORT}"
echo "  TEST_REDMINE_PORT:    ${TEST_PORT}"
echo ""

# Create worktree (create branch if it doesn't exist, checkout if it does)
if git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git worktree add "$WORKTREE_DIR" "$BRANCH"
else
  git worktree add -b "$BRANCH" "$WORKTREE_DIR"
fi

# Copy .env.example as base, then override with worktree-specific values
if [ -f .env.example ]; then
  cp .env.example "$WORKTREE_DIR/.env"
fi

# Write worktree-specific .env (append/override key values)
cat >> "$WORKTREE_DIR/.env" <<EOF

# --- Worktree-specific overrides (generated by scripts/new-worktree.sh) ---
COMPOSE_PROJECT_NAME=${PROJECT_NAME}
REDMINE_PORT=${BASE_PORT}
TEST_REDMINE_PORT=${TEST_PORT}
EOF

echo "Worktree ready."
echo ""
echo "To start this worktree's environment:"
echo "  cd ${WORKTREE_DIR}"
echo "  make start"
echo ""
echo "To remove this worktree later (from the main repo):"
echo "  make worktree-remove BRANCH=${BRANCH}"
echo "  # or: git worktree remove ${WORKTREE_DIR} && git branch -d ${BRANCH}"
